[package]
name = "digimatic"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
csv = "1.4.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
serialport = "4.8.1"
